In [7]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [9]:
x = np.ones(3)
x

array([1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [10]:
y = np.zeros(3)
y

array([0., 0., 0.])

## Q#3: Add x and y arrays.

In [11]:
x + y

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [34]:

print(x.ndim,x.shape,x.size,x.dtype)

1 (3,) 3 float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [12]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [13]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [14]:
z = z.reshape(3,1)
newArray = np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [15]:
for row in newArray:
    for var in row:
        print(var)


1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [16]:
np.flip(newArray)


array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [17]:
np.subtract(newArray, 1)

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [18]:
np.min(newArray), np.max(newArray)

(1, 16)

## Q#12: Print the first row of "newArray" using indexing.

In [19]:
newArray[0, :]


array([ 1, 11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [20]:
newArray[0,2]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [21]:
np.subtract(newArray, 1), newArray[0,0], newArray[1,1]

(array([[ 0, 10, 11],
        [ 1, 12, 13],
        [ 2, 14, 15]]),
 1,
 13)

## Q#15: Change the shape of "newArray" to (9,1).

In [22]:
newArray.reshape(9,1)

array([[ 1],
       [11],
       [12],
       [ 2],
       [13],
       [14],
       [ 3],
       [15],
       [16]])

## Q#16: Change the shape of "newArray" to (3,2).

In [23]:
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

In [31]:
reshaped_array = newArray.flatten()[:6].reshape(3, 2)
reshaped_array

array([[ 1, 11],
       [12,  2],
       [13, 14]])

# Well Done 🎉